### ISSUE TITLE
Modificar CI padrão para utilizar o Makefile terraform.inc

### ISSUE THREAD

**Issue by afonsoaugusto** [mentoriaiac/template-modulo-terraform#9]
# Modificar CI padrão para utilizar o Makefile terraform.inc

Hoje no nosso exemplo de [como utilizar o modulo](https://github.com/mentoriaiac/template-modulo-terraform/tree/main/how-to-use-this-module) nós temos a implementação base do repositório [Makefiles](https://github.com/mentoriaiac/Makefiles).

Porem hoje nós utilizamos no CI a implementação do binário terraform diretamente:
https://github.com/mentoriaiac/template-modulo-terraform/blob/af304123dec57699a40ab8bf91adebb0a98b6d3a/.github/workflows/ci.yml#L18-L32

Acho que seria legal no nosso CI padrão ter a execução do Makefile, ou no exemplo de como utilizar o modulo.

```yaml
 - name: Terraform Format 
   id: fmt 
   run: make fmt
   continue-on-error: true 

 - name: Terraform Init 
   id: init 
   run: make init
```

## DoD

- [ ] ter implementado na execução do terraform o makefile do Makefiles.
